services:
  client:
    build:
      context: ./client
      target: dev
    container_name: client
    restart: always
    command: yarn dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - ${CLIENT_PORT}:3000
    environment:
      NODE_ENV: development
      API_HOST: api
      API_PORT: 8000

  api:
    build: ./server
    container_name: api
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./server/app:/code/app
    ports:
      - ${API_PORT}:8000
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-todos}
      DB_HOST: ${DB_HOST:-db}
      DEBUG: 1
    depends_on:
      - db

  db:
    image: postgres:16.0
    container_name: db
    restart: always
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-todos}
